import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";

import ReduxProvider from "@/redux/Provider";
import AuthProvider from "@/auth/AuthProvider";
import Header from "@/components/Header";
import Box from "@mui/material/Box/Box";
import SideDrawer from "@/components/SideDrawer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ReduxProvider>
            <Box width={"100%"} minHeight={"100vh"} bgcolor={"lightskyblue"}>
              <Header />
              <SideDrawer />
              {children}
            </Box>
          </ReduxProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
